=== api-evangelist/lightspeed-pos/json-schema/restaurant-k-series-ape-standalone-payment-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "apeStandalonePayment",
  "description": "Payment to apply to an existing order.",
  "$id": "https://raw.githubusercontent.com/api-evangelist/lightspeed-pos/refs/heads/main/json-schema/restaurant-k-series-ape-standalone-payment-schema.json",
  "type": "object",
  "properties": {
    "iKaccountId": {
      "example": 0,
      "type": "integer",
      "format": "int64",
      "deprecated": true
    },
    "iKaccountIdentifier": {
      "example": "A1234.56",
      "description": "The ID of the account to apply this payment to.",
      "type": "string"
    },
    "thirdPartyPaymentReference": {
      "description": "A unique external reference provided for this order. This value will be sent back in the webhook.",
      "type": "string",
      "minLength": 1,
      "maxLength": 50,
      "example": "12345678901234"
    },
    "endpointId": {
      "description": "Endpoint ID for a unique webhook that has been created using [the webhook endpoint](https://api-docs.lsk.lightspeed.app/operation/operation-apecreatewebhookoo).",
      "type": "string",
      "example": "MY-AWESOME-ENDPOINT-ID"
    },
    "businessLocationId": {
      "description": "The unique identifier for the business location.",
      "type": "integer",
      "format": "int64",
      "example": 45454565682155
    },
    "taskTtlInMs": {
      "example": 60000,
      "description": "Maximum time to attempt delivery of this payment to the POS. In milliseconds. The minimum value is 60000ms (1 minute).",
      "type": "integer",
      "format": "int32"
    },
    "staffId": {
      "type": "integer",
      "format": "int64",
      "description": "The ID of the employee responsible for this payment."
    },
    "deviceId": {
      "description": "POS device to specifically receive this payment. If left null then all POS devices may receive the payment but only one will process it.",
      "type": "integer",
      "format": "int64",
      "example": 12345678980
    },
    "paymentMethod": {
      "example": "OOPAYMENT",
      "description": "Payment method code as configured by the merchant.",
      "type": "string"
    },
    "paymentAmount": {
      "example": 20.06,
      "description": "The total amount of the payment without tips.",
      "type": "number"
    },
    "tipAmount": {
      "example": 2.5,
      "description": "The tip amount, if any.",
      "type": "number"
    },
    "targetPrinterProfileId": {
      "example": 1773881235,
      "description": "The printer profile id to use for printing the receipt for this payment. If not provided, the default active printer profile for the business location will be used.",
      "type": "integer",
      "format": "int64"
    }
  },
  "required": [
    "businessLocationId",
    "endpointId",
    "paymentAmount",
    "thirdPartyPaymentReference"
  ]
}

=== api-evangelist/lightspeed-pos/examples/restaurant-k-series-ape-standalone-payment-example.json
{
  "iKaccountId": 0,
  "iKaccountIdentifier": "A1234.56",
  "thirdPartyPaymentReference": "12345678901234",
  "endpointId": "MY-AWESOME-ENDPOINT-ID",
  "businessLocationId": 45454565682155,
  "taskTtlInMs": 60000,
  "staffId": 37,
  "deviceId": 12345678980,
  "paymentMethod": "OOPAYMENT",
  "paymentAmount": 20.06,
  "tipAmount": 2.5,
  "targetPrinterProfileId": 1773881235
}
