=== api-evangelist/lightspeed-pos/json-schema/restaurant-k-series-ape-customer-info-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "apeCustomerInfo",
  "description": "apeCustomerInfo schema from Lightspeed Restaurant K Series API",
  "$id": "https://raw.githubusercontent.com/api-evangelist/lightspeed-pos/refs/heads/main/json-schema/restaurant-k-series-ape-customer-info-schema.json",
  "type": "object",
  "properties": {
    "firstName": {
      "example": "Jane",
      "description": "Customer first name.",
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "lastName": {
      "example": "Doe",
      "description": "Customer last name.",
      "type": "string"
    },
    "thirdPartyReference": {
      "example": "ZEN-7074522d-c71d-403f",
      "type": "string",
      "description": "The unique reference for this customer which can help to identify them later on. If the email is left empty, this should be empty as well."
    },
    "email": {
      "example": "jane.doe@example.com",
      "description": "The email address for this customer.",
      "type": "string"
    },
    "contactNumberAsE164": {
      "example": "+14155552671",
      "description": "The customer phone number in E164 format.",
      "type": "string"
    },
    "notes": {
      "example": "Notes about the customer.",
      "description": "The notes attached to the customer.",
      "type": "string"
    },
    "salutation": {
      "example": "Mr.",
      "description": "Salutation for the customer (Mr., Mrs., Dr., etc...).",
      "type": "string"
    },
    "sendEmailReceipts": {
      "example": true,
      "description": "Default value of emailNotification setting for new customers",
      "type": "boolean"
    },
    "emailNotification": {
      "default": "DONT_CHANGE",
      "description": "Update the customer email notification setting. For example, sendEmailReceipts = true, emailNotification = DONT_CHANGE - sends receipt email for all users who haven't disabled it in the Backoffice. sendEmailReceipts = false, emailNotification = DONT_CHANGE - will not send receipt email for all users except those who enabled it in the Backoffice",
      "enum": [
        "ENABLE",
        "DISABLE",
        "DONT_CHANGE"
      ],
      "type": "string"
    }
  },
  "required": [
    "firstName"
  ]
}

=== api-evangelist/lightspeed-pos/examples/restaurant-k-series-ape-customer-info-example.json
{
  "firstName": "Jane",
  "lastName": "Doe",
  "thirdPartyReference": "ZEN-7074522d-c71d-403f",
  "email": "jane.doe@example.com",
  "contactNumberAsE164": "+14155552671",
  "notes": "Notes about the customer.",
  "salutation": "Mr.",
  "sendEmailReceipts": true,
  "emailNotification": "DONT_CHANGE"
}
