=== api-evangelist/lightspeed-pos/json-schema/restaurant-k-series-ape-local-order-item-line-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "apeLocalOrderItemLine",
  "description": "apeLocalOrderItemLine schema from Lightspeed Restaurant K Series API",
  "$id": "https://raw.githubusercontent.com/api-evangelist/lightspeed-pos/refs/heads/main/json-schema/restaurant-k-series-ape-local-order-item-line-schema.json",
  "type": "object",
  "properties": {
    "quantity": {
      "example": 1,
      "description": "Quantity of item to be ordered.",
      "type": "integer",
      "format": "int32"
    },
    "sku": {
      "example": "UGG-BB-PUR-06",
      "maxLength": 25,
      "description": "The SKU of the item to be ordered.",
      "type": "string"
    },
    "customItemName": {
      "example": "My Custom Item Name",
      "description": "The custom name to be used, if overwriting is permitted for this item.",
      "type": "string"
    },
    "customItemPrice": {
      "example": 10.0,
      "description": "The custom price to be used, if custom pricing is permitted for this item.",
      "type": "number"
    },
    "discountAmountOverride": {
      "description": "The custom discount amount applied to this item. Only one of `discountAmountOverride` or `discountPercentOverride` can be set. Must be used in conjunction with a [discountCode](https://api-docs.lsk.lightspeed.app/operation/operation-apelocalorder#operation-apelocalorder-body-application-json-items-discountcode) and this discount must be configured as a \"manual discount\" in the POS. See [Understanding Discounts](https://k-series-support.lightspeedhq.com/hc/en-us/articles/1260804657089-Understanding-discounts).",
      "type": "number",
      "example": 5.0
    },
    "discountPercentOverride": {
      "description": "The custom percentage discount applied to this item. Only one of `discountAmountOverride` or `discountPercentOverride` can be set. Must be used in conjunction with a [discountCode](https://api-docs.lsk.lightspeed.app/operation/operation-apelocalorder#operation-apelocalorder-body-application-json-items-discountcode) and this discount must be configured as a \"manual discount\" in the POS. See [Understanding Discounts](https://k-series-support.lightspeedhq.com/hc/en-us/articles/1260804657089-Understanding-discounts).",
      "type": "number",
      "example": 10.0
    },
    "modifiers": {
      "description": "Collection of [modifiers](https://api-docs.lsk.lightspeed.app/operation/operation-apeloadallmodifiers) to be applied to this item.",
      "type": "array",
      "items": {
        "properties": {
          "modifierId": {
            "example": "236025632784492",
            "description": "Modifier ID to be applied to this item.",
            "type": "string"
          }
        },
        "type": "object"
      }
    },
    "discountCode": {
      "example": "FIVEPERCENT",
      "description": "The discount code being applied to this item, if applicable.",
      "type": "string"
    },
    "course": {
      "example": 2,
      "description": "The course number for this item, if applicable.",
      "minimum": 0,
      "type": "integer",
      "format": "int32"
    },
    "subItems": {
      "description": "The sub-items applied to this item.",
      "items": {
        "required": [
          "quantity",
          "sku"
        ],
        "properties": {
          "quantity": {
            "example": 1,
            "description": "Quantity of sub-item to be ordered.",
            "type": "integer",
            "format": "int32"
          },
          "sku": {
            "example": "ABC-123",
            "maxLength": 25,
            "description": "The SKU of the sub-item to be ordered.",
            "type": "string"
          },
          "customItemName": {
            "example": "My Custom Sub-Item Name",
            "description": "The custom name to be used if overwriting is supported for this sub-item.",
            "type": "string"
          },
          "customItemPrice": {
            "example": 2.0,
            "description": "The custom price to be used if overwriting is supported for this sub-item.",
            "type": "number"
          },
          "modifiers": {
            "description": "Collection of modifiers to be applied to this sub-item.",
            "items": {
              "properties": {
                "modifierId": {
                  "example": "236025632784492",
                  "description": "Modifier ID to be applied to this item.",
                  "type": "string"
                }
              },
              "type": "object"
            },
            "type": "array"
          },
          "subItems": {
            "description": "Product modifiers applied to this item.",
            "items": {
              "required": [
                "quantity",
                "sku"
              ],
              "properties": {
                "quantity": {
                  "example": 1,
                  "description": "Quantity of sub-item to be ordered.",
                  "type": "integer",
                  "format": "int32"
                },
                "sku": {
                  "example": "ABC-123",
                  "maxLength": 25,
                  "description": "The SKU of the sub-item to be ordered.",
                  "type": "string"
                },
                "customItemName": {
                  "example": "My Custom Sub-Item Name",
                  "description": "The custom name to be used if overwriting is supported for this sub-item.",
                  "type": "string"
                },
                "customItemPrice": {
                  "example": 2.0,
                  "description": "The custom price to be used if overwriting is supported for this sub-item.",
                  "type": "number"
                },
                "modifiers": {
                  "description": "Collection of modifiers to be applied to this sub-item.",
                  "items": {
                    "properties": {
                      "modifierId": {
                        "example": "236025632784492",
                        "description": "Modifier ID to be applied to this item.",
                        "type": "string"
                      }
                    },
                    "type": "object"
                  },
                  "type": "array"
                },
                "subItems": {
                  "description": "Product modifiers applied to this item.",
                  "items": {
                    "required": [
                      "quantity",
                      "sku"
                    ],
                    "properties": {
                      "quantity": {
                        "example": 1,
                        "description": "Quantity of sub-item to be ordered.",
                        "type": "integer",
                        "format": "int32"
                      },
                      "sku": {
                        "example": "ABC-123",
                        "maxLength": 25,
                        "description": "The SKU of the sub-item to be ordered.",
                        "type": "string"
                      },
                      "customItemName": {
                        "example": "My Custom Sub-Item Name",
                        "description": "The custom name to be used if overwriting is supported for this sub-item.",
                        "type": "string"
                      },
                      "customItemPrice": {
                        "example": 2.0,
                        "description": "The custom price to be used if overwriting is supported for this sub-item.",
                        "type": "number"
                      },
                      "modifiers": {
                        "description": "Collection of modifiers to be applied to this sub-item.",
                        "items": {
                          "properties": {
                            "modifierId": {
                              "example": "236025632784492",
                              "description": "Modifier ID to be applied to this item.",
                              "type": "string"
                            }
                          },
                          "type": "object"
                        },
                        "type": "array"
                      },
                      "subItems": {
                        "description": "Product modifiers applied to this item.",
                        "items": {
                          "required": [
                            "quantity",
                            "sku"
                          ],
                          "properties": {
                            "quantity": {
                              "example": 1,
                              "description": "Quantity of sub-item to be ordered.",
                              "type": "integer",
                              "format": "int32"
                            },
                            "sku": {
                              "example": "ABC-123",
                              "maxLength": 25,
                              "description": "The SKU of the sub-item to be ordered.",
                              "type": "string"
                            },
                            "customItemName": {
                              "example": "My Custom Sub-Item Name",
                              "description": "The custom name to be used if overwriting is supported for this sub-item.",
                              "type": "string"
                            },
                            "customItemPrice": {
                              "example": 2.0,
                              "description": "The custom price to be used if overwriting is supported for this sub-item.",
                              "type": "number"
                            },
                            "modifiers": {
                              "description": "Collection of modifiers to be applied to this sub-item.",
                              "items": {
                                "type": "object"
                              },
                              "type": "array"
                            },
                            "subItems": {
                              "description": "Product modifiers applied to this item.",
                              "items": {
                                "type": "object"
                              },
                              "type": "array"
                            }
                          },
                          "type": "object"
                        },
                        "type": "array"
                      }
                    },
                    "type": "object"
                  },
                  "type": "array"
                }
              },
              "type": "object"
            },
            "type": "array"
          }
        },
        "type": "object"
      },
      "type": "array"
    }
  },
  "required": [
    "quantity",
    "sku"
  ]
}

=== api-evangelist/lightspeed-pos/examples/restaurant-k-series-ape-local-order-item-line-example.json
{
  "quantity": 1,
  "sku": "UGG-BB-PUR-06",
  "customItemName": "My Custom Item Name",
  "customItemPrice": 10.0,
  "discountAmountOverride": 5.0,
  "discountPercentOverride": 10.0,
  "modifiers": [
    {
      "modifierId": "236025632784492"
    }
  ],
  "discountCode": "FIVEPERCENT",
  "course": 2,
  "subItems": [
    {
      "quantity": 1,
      "sku": "ABC-123",
      "customItemName": "My Custom Sub-Item Name",
      "customItemPrice": 2.0,
      "modifiers": [
        {
          "modifierId": "236025632784492"
        }
      ],
      "subItems": [
        {
          "quantity": 1,
          "sku": "ABC-123",
          "customItemName": "My Custom Sub-Item Name",
          "customItemPrice": 2.0,
          "modifiers": [],
          "subItems": []
        }
      ]
    }
  ]
}
